{% set name = "libconfig" %}
{% set version = "1.7.3" %}
{% set sha256 = "68757e37c567fd026330c8a8449aa5f9cac08a642f213f2687186b903bd7e94e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/hyperrealm/{{ name }}/archive/v{{ version }}.tar.gz
  fn: v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake     # [not win]
    - autoconf     # [not win]
    - libtool      # [not win]
    - make         # [not win]
    - texinfo      # [not win]
    - ninja        # [win]
    - cmake        # [win]
    - msinttypes   # [win]

test:
  commands:
    - test -f $PREFIX/lib/libconfig++.so  # [linux]
    - test -f $PREFIX/lib/libconfig++.dylib  # [osx]

about:
  home: http://hyperrealm.com/libconfig/libconfig.html
  license: LGPL-2.1-only
  license_file: COPYING.LIB
  summary: 'C/C++ Configuration File Library'

extra:
  recipe-maintainers:
    - lomereiter
