{% set name = "libconfig" %}
{% set version = "1.7.2" %}
{% set sha256 = "7c3c7a9c73ff3302084386e96f903eb62ce06953bb1666235fac74363a16fad9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://hyperrealm.github.io/libconfig/dist/libconfig-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - msinttypes   # [win]
    - ninja
    - cmake

test:
  commands:
    - test -f $PREFIX/lib/libconfig++.so  # [linux]
    - test -f $PREFIX/lib/libconfig++.dylib  # [osx]

about:
  home: http://hyperrealm.com/libconfig/libconfig.html
  license: LGPL-2.1
  license_file: COPYING.LIB
  summary: 'C/C++ Configuration File Library'

extra:
  recipe-maintainers:
    - lomereiter
