{% set name = "libconfig" %}
{% set version = "1.8" %}
{% set sha256 = "22e13253e652ec583ba0dd5b474bd9c7bd85dc724f2deb0d76a6299c421358ef" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/hyperrealm/{{ name }}/archive/v{{ version }}.tar.gz
  fn: v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - automake     # [not win]
    - autoconf     # [not win]
    - libtool      # [not win]
    - make         # [not win]
    - texinfo      # [not win]
    - ninja        # [win]
    - cmake        # [win]
    - msinttypes   # [win]

test:
  commands:
    - test -f $PREFIX/lib/libconfig++.so  # [linux]
    - test -f $PREFIX/lib/libconfig++.dylib  # [osx]

about:
  home: http://hyperrealm.com/libconfig/libconfig.html
  license: LGPL-2.1-only
  license_file: COPYING.LIB
  summary: 'C/C++ Configuration File Library'

extra:
  recipe-maintainers:
    - lomereiter
