{% set name = "libconfig" %}
{% set version = "1.6" %}
{% set sha256 = "18739792eb463d73525d7aea9b0a48b14106fae1cfec09aedc668d8c1079adf1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/hyperrealm/libconfig/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}

test:
  commands:
    - test -f $PREFIX/lib/libconfig++.so  # [linux]
    - test -f $PREFIX/lib/libconfig++.dylib  # [osx]

about:
  home: http://hyperrealm.com/libconfig/libconfig.html
  license: LGPL-2.1
  license_file: COPYING.LIB
  summary: 'C/C++ Configuration File Library'

extra:
  recipe-maintainers:
    - lomereiter
