travis:
  secure:
    BINSTAR_TOKEN: Me6T9Sw1iBqo3sYKNkzvP3zLa3jpyIpSbCw21Hjp2xtqBxYUzh6v06ey6Tjam5HA/GM7Tb0ELxRdGD244RjDPNyBOTMNHJa5RcCDBAysSzT79zOzgd9y5fFwpR/NTAj3DSvE0ApTiWUC7l3IQqtRrO2wqZXrj5+bMcEQ4nJa4qF3Pwe/wtnoWRXKuNtpy4qHdte+8PLaHBjVbEExy0eL6IW/dvwXLtnwlvcdSJZs8trg7UxN4xkyAbLfZ5vYJeIoahUmMLiHXENQ3ZDr1GH+zpO5OITggVjT8myuDZCwOxNs2Fr1OxmAZZZzv73REnkS19OB4lQV0OZDKJduxHmBeE+x+VJXmlVYwF4ycoz+tftfcIb3r/HTcr740cg28QY23YNMLUBzRlZvpopwhUeBwnM1qOiHsFnHsnxuGfcAetm/WVir2lsuwzamJuLUShpw4d3khBjbRc+gSWiaWKSWgvrvB1KzOTdG17wBJVJ4czwmszzoA1Que/WRHZWQL9QMJThPJC8ziqKjw3ZOa4CRsEIwVlVjYJ4yj2oC3aNK1zg0QCI5Ma2VhjF3YQqeoAFRN/7EXOsaG2OyFdZpZoGQw0tAmagbv5RAtk38kNRpKOuBXNzv4bOAILkKIwCoYFh3zKZ0QOn1wVK3/ITenjO8PlIHB4cCLofvjBAV+dQYuRg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
