travis:
  secure:
    BINSTAR_TOKEN: xdOjq/B44h/Hs3c46HWca7ePdTvrVvqWNYeUv2Ui03Qz76oBkgyWmS9WRRSC1mvsHVkdDxlaP4i5rU9TRh35N8sVlIFRFqToJWnPsYdngq7Rbj5TJ2cWAsMuefv1cFT2ZYX7GTNXBRF4sKSuiTOOUGjEK9dBCAYO6y1xhc+Pi6+f8tsMgnualOmXux3Y3ym2/gFD4+m37vD9Sv3kxAQ4JPrhBlczT2NEuJExKlf19Ew0cSLOwcKOIfCgRQpjCcANvg+AWNYvKkLMc7st8CrwXWVHP9GrjEV33KK7wEmN23R1bTUAAsCHIdor0RT2kVCbd49fGzhGXANMkXGVJELkrpWjE+5lxH7Fj8Y1oOf4pBbuu+cBvP+FoSeR/0v5k5+zvot2Vw3YfqLh9NXkolgkeAlh2MHblMBt3RhZZXyLkXrINMh4AgaoncpexxAjNsh2UXUwZxPw2ozeGpBZJwpWh0LGW6gsr139XTXSKOoDFTet7TYUh8b55OkUSii/grFkYxXLUMCgYkyaV8U2+Dqp2ntOxHEIWwxeclt+iweKsI0Laye6XqDNSQA01rbFKInzI4rxJDVAcIp2+u5bKeEMEIQdCpr2K1rz9Z86SE2bEq++AaTeBtTS7TgFgmW5n9ftgiJR+DBRjzA++pgW3/Lyd3MwqCUcPoBM0stUGrH54vw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
